name: Price Tracker

on:
  schedule:
    - cron: "0 17,21,1,5 * * *" # Runs at 18:30, 22:30, 02:30, 06:30 UTC
  workflow_dispatch: # Allows manual runs

# Set the permissions to allow pushing to the repository
permissions:
  contents: write
  pull-requests: write

jobs:
  track-prices:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          # Fetch all history so we can amend the last commit
          fetch-depth: 0
          # Use the GitHub token for authentication
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run price tracker
        env:
          WHC_FROM_EMAIL: ${{ secrets.WHC_FROM_EMAIL }}
          WHC_TO_EMAIL: ${{ secrets.WHC_TO_EMAIL }}
          WHC_EMAIL_PASS: ${{ secrets.WHC_EMAIL_PASS }}
        run: python main.py

      - name: Commit and push if data changed
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # Get the current date and time for the commit message
          CURRENT_DATE=$(date +"%Y-%m-%d %H:%M:%S")

          # Stage all changes in the data directory
          git add data/

          # Check if there are any changes to commit
          if ! git diff --staged --quiet; then
            # Create a new commit with a descriptive message
            git commit --amend --no-edit
            
            # Push the changes using the GitHub token
            git push -f
          else
            echo "No changes to commit"
          fi
